apiVersion: v1
kind: ConfigMap
data:
  DB_USERNAME: "ct_admin"
  DB_NAME: "geoconnections"
  DB_HOST: "postgres.udaconnect.svc.cluster.local"
  DB_PORT: "5432"
metadata:
  name: db-env
  namespace: udaconnect
